export 'assignment/assignment.dart';
export 'backpack/backpack.dart';
export 'class_detail/class_detail.dart';
export 'home/home.dart';
export 'login/login.dart';
export 'main/main.dart';
export 'more/more.dart';
export 'splash/splash.dart';
export 'study/study.dart';
